version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/dockerfile
    image: ubuntu:latest
    restart: always
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - netwrk

  webserver:
    image: nginx:stable-alpine
    container_name: webserver
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/public
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - netwrk

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - netwrk

  npm:
    image: node:16
    #hostname: vite.local
    ports:
      - "5173:5173"
    expose:
      - "5173"
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: [sh, -c, "cd /var/www && npm install && npm run dev"]
    depends_on:
      webserver:
        condition: service_started

networks:
  netwrk:
    driver: bridge

volumes:
  db:
    driver: local
